package theme

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"syncpaper/internal/config"
)

// GetCacheDir returns ~/.cache/syncpaper
func GetCacheDir() string {
	cacheHome := os.Getenv("XDG_CACHE_HOME")
	if cacheHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return filepath.Join(".", ".cache", "syncpaper")
		}
		cacheHome = filepath.Join(home, ".cache")
	}
	return filepath.Join(cacheHome, "syncpaper")
}

// ExportTheme writes all configured theme files and triggers live desktop reloads
func ExportTheme(cfg *config.Config, p *Palette, wallpaperPath string) error {
	cacheDir := GetCacheDir()
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return fmt.Errorf("failed to create cache directory %s: %w", cacheDir, err)
	}

	colorsJSONPath := filepath.Join(cacheDir, "colors.json")

	// 1. Pywal / Wallust compatible colors.json
	if cfg.Theming.ExportPywal {
		schema := p.ToPywalSchema(wallpaperPath)
		data, err := json.MarshalIndent(schema, "", "  ")
		if err == nil {
			_ = os.WriteFile(colorsJSONPath, data, 0644)
			// Mirror to standard ~/.cache/wal/colors.json for VS Code (Wal Theme), Pywalfox, etc.
			walDir := filepath.Join(filepath.Dir(cacheDir), "wal")
			if err := os.MkdirAll(walDir, 0755); err == nil {
				_ = os.WriteFile(filepath.Join(walDir, "colors.json"), data, 0644)
			}
		}
	}

	// 2. Shell environment script (colors.sh)
	exportColorsSH(cacheDir, p, wallpaperPath)

	// 3. Hyprland colors config
	if cfg.Theming.ExportHyprland {
		exportHyprlandColors(cacheDir, p)
	}

	// 4. Waybar CSS
	if cfg.Theming.ExportWaybar {
		exportWaybarCSS(cacheDir, p)
	}

	// 5. Kitty terminal colors
	if cfg.Theming.ExportKitty {
		exportKittyColors(cacheDir, p)
	}

	// 6. Alacritty colors
	if cfg.Theming.ExportAlacritty {
		exportAlacrittyColors(cacheDir, p)
	}

	// 7. Foot colors
	if cfg.Theming.ExportFoot {
		exportFootColors(cacheDir, p)
	}

	// 8. Trigger desktop reloads & hooks
	TriggerReloads(cfg, p, wallpaperPath, colorsJSONPath)

	return nil
}

func exportColorsSH(cacheDir string, p *Palette, wallpaperPath string) {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# Generated by syncpaper\n")
	b.WriteString(fmt.Sprintf("export WALLPAPER=\"%s\"\n", wallpaperPath))
	b.WriteString(fmt.Sprintf("export BACKGROUND=\"%s\"\n", p.Background.Hex()))
	b.WriteString(fmt.Sprintf("export FOREGROUND=\"%s\"\n", p.Foreground.Hex()))
	b.WriteString(fmt.Sprintf("export ACCENT=\"%s\"\n", p.Accent.Hex()))
	b.WriteString(fmt.Sprintf("export ACCENT_SECONDARY=\"%s\"\n", p.AccentSecondary.Hex()))
	b.WriteString(fmt.Sprintf("export SURFACE=\"%s\"\n", p.Surface.Hex()))
	for i := 0; i < 16; i++ {
		b.WriteString(fmt.Sprintf("export COLOR%d=\"%s\"\n", i, p.Colors[i].Hex()))
	}
	_ = os.WriteFile(filepath.Join(cacheDir, "colors.sh"), []byte(b.String()), 0755)
}

func exportHyprlandColors(cacheDir string, p *Palette) {
	var b strings.Builder
	b.WriteString("# Generated by syncpaper\n")
	b.WriteString(fmt.Sprintf("$background = %s\n", p.Background.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$foreground = %s\n", p.Foreground.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$surface = %s\n", p.Surface.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$accent = %s\n", p.Accent.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$accent_secondary = %s\n", p.AccentSecondary.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$active_border_1 = %s\n", p.ActiveBorder.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$active_border_2 = %s\n", p.AccentSecondary.HyprlandHex()))
	b.WriteString(fmt.Sprintf("$inactive_border = %s\n", p.InactiveBorder.HyprlandHex()))

	_ = os.WriteFile(filepath.Join(cacheDir, "hyprland-colors.conf"), []byte(b.String()), 0644)
}

func exportWaybarCSS(cacheDir string, p *Palette) {
	var b strings.Builder
	b.WriteString("/* Generated by syncpaper */\n")
	b.WriteString(fmt.Sprintf("@define-color background %s;\n", p.Background.Hex()))
	b.WriteString(fmt.Sprintf("@define-color foreground %s;\n", p.Foreground.Hex()))
	b.WriteString(fmt.Sprintf("@define-color surface %s;\n", p.Surface.Hex()))
	b.WriteString(fmt.Sprintf("@define-color accent %s;\n", p.Accent.Hex()))
	b.WriteString(fmt.Sprintf("@define-color accent_secondary %s;\n", p.AccentSecondary.Hex()))
	b.WriteString(fmt.Sprintf("@define-color active_border %s;\n", p.ActiveBorder.Hex()))
	b.WriteString(fmt.Sprintf("@define-color inactive_border %s;\n", p.InactiveBorder.Hex()))

	_ = os.WriteFile(filepath.Join(cacheDir, "waybar-colors.css"), []byte(b.String()), 0644)
}

func exportKittyColors(cacheDir string, p *Palette) {
	var b strings.Builder
	b.WriteString("# Generated by syncpaper\n")
	b.WriteString(fmt.Sprintf("background %s\n", p.Background.Hex()))
	b.WriteString(fmt.Sprintf("foreground %s\n", p.Foreground.Hex()))
	b.WriteString(fmt.Sprintf("cursor %s\n", p.Cursor.Hex()))
	b.WriteString(fmt.Sprintf("selection_background %s\n", p.Accent.Hex()))
	b.WriteString(fmt.Sprintf("selection_foreground %s\n", p.Background.Hex()))
	b.WriteString(fmt.Sprintf("active_border_color %s\n", p.ActiveBorder.Hex()))
	b.WriteString(fmt.Sprintf("inactive_border_color %s\n", p.InactiveBorder.Hex()))
	for i := 0; i < 16; i++ {
		b.WriteString(fmt.Sprintf("color%d %s\n", i, p.Colors[i].Hex()))
	}
	kittyFile := filepath.Join(cacheDir, "kitty-colors.conf")
	_ = os.WriteFile(kittyFile, []byte(b.String()), 0644)
}

func exportAlacrittyColors(cacheDir string, p *Palette) {
	var b strings.Builder
	b.WriteString("# Generated by syncpaper\n")
	b.WriteString("[colors.primary]\n")
	b.WriteString(fmt.Sprintf("background = \"%s\"\n", p.Background.Hex()))
	b.WriteString(fmt.Sprintf("foreground = \"%s\"\n", p.Foreground.Hex()))
	b.WriteString("\n[colors.cursor]\n")
	b.WriteString(fmt.Sprintf("cursor = \"%s\"\n", p.Cursor.Hex()))
	b.WriteString(fmt.Sprintf("text = \"%s\"\n", p.Background.Hex()))
	b.WriteString("\n[colors.normal]\n")
	names := []string{"black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"}
	for i := 0; i < 8; i++ {
		b.WriteString(fmt.Sprintf("%s = \"%s\"\n", names[i], p.Colors[i].Hex()))
	}
	b.WriteString("\n[colors.bright]\n")
	for i := 0; i < 8; i++ {
		b.WriteString(fmt.Sprintf("%s = \"%s\"\n", names[i], p.Colors[i+8].Hex()))
	}

	_ = os.WriteFile(filepath.Join(cacheDir, "alacritty-colors.toml"), []byte(b.String()), 0644)
}

func exportFootColors(cacheDir string, p *Palette) {
	var b strings.Builder
	b.WriteString("# Generated by syncpaper\n[colors]\n")
	b.WriteString(fmt.Sprintf("background=%s\n", strings.TrimPrefix(p.Background.Hex(), "#")))
	b.WriteString(fmt.Sprintf("foreground=%s\n", strings.TrimPrefix(p.Foreground.Hex(), "#")))
	for i := 0; i < 8; i++ {
		b.WriteString(fmt.Sprintf("regular%d=%s\n", i, strings.TrimPrefix(p.Colors[i].Hex(), "#")))
	}
	for i := 0; i < 8; i++ {
		b.WriteString(fmt.Sprintf("bright%d=%s\n", i, strings.TrimPrefix(p.Colors[i+8].Hex(), "#")))
	}

	_ = os.WriteFile(filepath.Join(cacheDir, "foot-colors.ini"), []byte(b.String()), 0644)
}

// TriggerReloads refreshes running desktop components and signals
func TriggerReloads(cfg *config.Config, p *Palette, wallpaperPath string, colorsJSONPath string) {
	// 1. GTK dark/light mode preference
	if cfg.Theming.UpdateGTKTheme {
		scheme := "prefer-dark"
		if !p.IsDark {
			scheme = "prefer-light"
		}
		_ = exec.Command("gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme).Run()
	}

	// 2. Waybar instant CSS reload (SIGUSR2)
	_ = exec.Command("pkill", "-SIGUSR2", "waybar").Run()

	// 3. Kitty live colors reload (asynchronously with short timeout so it never blocks)
	kittyFile := filepath.Join(GetCacheDir(), "kitty-colors.conf")
	go func() {
		ctx, cancel := context.WithTimeout(context.Background(), 300*time.Millisecond)
		defer cancel()
		_ = exec.CommandContext(ctx, "kitty", "@", "set-colors", "-a", kittyFile).Run()
	}()

	// 4. Hyprland reload
	if os.Getenv("HYPRLAND_INSTANCE_SIGNATURE") != "" {
		_ = exec.Command("hyprctl", "reload").Run()
	}

	// 5. User custom hook script
	if cfg.Theming.HookScript != "" {
		hookPath := config.ExpandPath(cfg.Theming.HookScript)
		if info, err := os.Stat(hookPath); err == nil && (info.Mode()&0111 != 0) {
			cmd := exec.Command(hookPath, wallpaperPath, colorsJSONPath)
			_ = cmd.Start()
		}
	}
}
