#!/usr/bin/env bash
# ==============================================================================
# syncpaper on_theme.sh hook script
# Triggered automatically after wallpaper rotation and theme extraction.
# Arguments:
#   $1 = Active wallpaper path
#   $2 = Path to colors.json (~/.cache/syncpaper/colors.json)
# ==============================================================================

WALLPAPER="$1"
COLORS_JSON="$2"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/syncpaper"
COLORS_SH="$CACHE_DIR/colors.sh"

# Source extracted color variables ($BACKGROUND, $FOREGROUND, $ACCENT, etc.)
if [ -f "$COLORS_SH" ]; then
    # shellcheck source=/dev/null
    . "$COLORS_SH"
else
    exit 0
fi

# ------------------------------------------------------------------------------
# 1. VS Code / Code - OSS / VSCodium Real-Time Theme Sync
# ------------------------------------------------------------------------------
if command -v jq >/dev/null 2>&1; then
    VSCODE_SETTINGS_PATHS=(
        "$HOME/.config/Code - OSS/User/settings.json"
        "$HOME/.config/Code/User/settings.json"
        "$HOME/.config/VSCodium/User/settings.json"
        "$HOME/.config/Code - Insiders/User/settings.json"
    )

    for settings_file in "${VSCODE_SETTINGS_PATHS[@]}"; do
        if [ -f "$settings_file" ]; then
            # Ensure file is valid JSON before modifying
            if ! jq empty "$settings_file" 2>/dev/null; then
                echo "{}" > "$settings_file"
            fi

            tmp_settings=$(mktemp)
            jq --arg bg "$BACKGROUND" \
               --arg fg "$FOREGROUND" \
               --arg surface "$SURFACE" \
               --arg accent "$ACCENT" \
               --arg accent2 "$ACCENT_SECONDARY" \
               '.["workbench.colorCustomizations"] = ((.["workbench.colorCustomizations"] // {}) + {
                   "editor.background": $bg,
                   "editor.foreground": $fg,
                   "activityBar.background": $bg,
                   "activityBar.foreground": $accent,
                   "activityBar.activeBorder": $accent,
                   "sideBar.background": $surface,
                   "sideBar.foreground": $fg,
                   "sideBarTitle.foreground": $accent,
                   "statusBar.background": $accent,
                   "statusBar.foreground": $bg,
                   "titleBar.activeBackground": $bg,
                   "titleBar.activeForeground": $fg,
                   "tab.activeBackground": $surface,
                   "tab.activeBorder": $accent,
                   "tab.activeForeground": $fg,
                   "tab.inactiveBackground": $bg,
                   "tab.inactiveForeground": $fg,
                   "terminal.background": $bg,
                   "terminal.foreground": $fg
               })' "$settings_file" > "$tmp_settings" && mv "$tmp_settings" "$settings_file"
        fi
    done
fi

# ------------------------------------------------------------------------------
# 2. GTK 3 & GTK 4 Dynamic CSS Variables
# ------------------------------------------------------------------------------
GTK_CSS="$CACHE_DIR/gtk-colors.css"
cat <<EOF > "$GTK_CSS"
/* Generated by syncpaper */
@define-color accent_color $ACCENT;
@define-color accent_bg_color $ACCENT;
@define-color accent_fg_color $BACKGROUND;
@define-color window_bg_color $BACKGROUND;
@define-color window_fg_color $FOREGROUND;
@define-color view_bg_color $SURFACE;
@define-color view_fg_color $FOREGROUND;
@define-color headerbar_bg_color $SURFACE;
@define-color headerbar_fg_color $FOREGROUND;
@define-color headerbar_border_color $ACCENT_SECONDARY;
EOF

# ------------------------------------------------------------------------------
# 3. Notification Daemons (Dunst, Mako, SwayNC)
# ------------------------------------------------------------------------------
if pgrep -x dunst >/dev/null 2>&1; then
    dunstctl reload 2>/dev/null || pkill -SIGUSR2 dunst 2>/dev/null
fi

if pgrep -x mako >/dev/null 2>&1; then
    makoctl reload 2>/dev/null
fi

if command -v swaync-client >/dev/null 2>&1 && pgrep -x swaync >/dev/null 2>&1; then
    swaync-client -R -rs 2>/dev/null
fi

# ------------------------------------------------------------------------------
# 4. Firefox (Pywalfox)
# ------------------------------------------------------------------------------
if command -v pywalfox >/dev/null 2>&1; then
    pywalfox update 2>/dev/null &
fi

# ------------------------------------------------------------------------------
# 5. Spotify (Spicetify)
# ------------------------------------------------------------------------------
if command -v spicetify >/dev/null 2>&1; then
    spicetify apply -n 2>/dev/null &
fi
